services:
  - type: web
    name: troca-xml-web
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 900 --workers 1 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
